-- MySQL Script generated by MySQL Workbench
-- Thu May  3 17:01:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Portal` ;

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portal` DEFAULT CHARACTER SET utf8 ;
USE `Portal` ;

-- -----------------------------------------------------
-- Table `Portal`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`usuario` ;

CREATE TABLE IF NOT EXISTS `Portal`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `password` VARCHAR(255) BINARY NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `fecha` DATE NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`genero` ;

CREATE TABLE IF NOT EXISTS `Portal`.`genero` (
  `idGenero` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`datos_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`datos_usuario` ;

CREATE TABLE IF NOT EXISTS `Portal`.`datos_usuario` (
  `idDatosUsuario` INT NOT NULL,
  `idGenero` TINYINT(1) NOT NULL,
  `nombre` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `apellido_1` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `apellido_2` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `telefono` CHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`idDatosUsuario`, `idGenero`),
  CONSTRAINT `fk_datos_usuario_genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `Portal`.`genero` (`idGenero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`provincias` ;

CREATE TABLE IF NOT EXISTS `Portal`.`provincias` (
  `idProvincias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`idProvincias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`direccion` ;

CREATE TABLE IF NOT EXISTS `Portal`.`direccion` (
  `idDireccion` INT NOT NULL,
  `calle` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `numeroPortal` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `ptr` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `codigoPostal` CHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `ciudad` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `provincias_idprovincias` INT NOT NULL,
  `pais` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`idDireccion`, `provincias_idprovincias`),
  INDEX `fk_direccion_provincias1_idx` (`provincias_idprovincias` ASC),
  CONSTRAINT `fk_direccion_provincias1`
    FOREIGN KEY (`provincias_idprovincias`)
    REFERENCES `Portal`.`provincias` (`idProvincias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`secciones` ;

CREATE TABLE IF NOT EXISTS `Portal`.`secciones` (
  `idSecciones` TINYINT(20) NOT NULL AUTO_INCREMENT,
  `nombre_seccion` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idSecciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`tiempo_cambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`tiempo_cambio` ;

CREATE TABLE IF NOT EXISTS `Portal`.`tiempo_cambio` (
  `idTiempoCambio` INT NOT NULL AUTO_INCREMENT,
  `tiempo` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idTiempoCambio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`post` ;

CREATE TABLE IF NOT EXISTS `Portal`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `idUsuarioPost` INT NOT NULL,
  `secciones_idsecciones` TINYINT(20) NOT NULL,
  `tiempo_cambio_idTiempoCambio` INT NOT NULL,
  `titulo` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `comentario` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `precio` VARCHAR(10) NULL,
  `fechaPost` DATE NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_post_secciones1_idx` (`secciones_idsecciones` ASC),
  INDEX `fk_post_tiempo_cambio1_idx` (`tiempo_cambio_idTiempoCambio` ASC),
  CONSTRAINT `fk_post_secciones1`
    FOREIGN KEY (`secciones_idsecciones`)
    REFERENCES `Portal`.`secciones` (`idSecciones`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tiempo_cambio1`
    FOREIGN KEY (`tiempo_cambio_idTiempoCambio`)
    REFERENCES `Portal`.`tiempo_cambio` (`idTiempoCambio`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`imagenes` ;

CREATE TABLE IF NOT EXISTS `Portal`.`imagenes` (
  `post_idPost` INT NOT NULL,
  `ruta` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `texto` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  INDEX `fk_imagenes_posts_idx` (`post_idPost` ASC),
  PRIMARY KEY (`ruta`, `post_idPost`),
  CONSTRAINT `fk_imagenes_posts`
    FOREIGN KEY (`post_idPost`)
    REFERENCES `Portal`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`post_denunciados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`post_denunciados` ;

CREATE TABLE IF NOT EXISTS `Portal`.`post_denunciados` (
  `idPostDenunciado` INT NOT NULL,
  `idUsuarioDenunciante` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `motivo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idPostDenunciado`),
  UNIQUE INDEX `idUsuarioDenunciante_UNIQUE` (`idUsuarioDenunciante` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`usuarios_bloqueados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`usuarios_bloqueados` ;

CREATE TABLE IF NOT EXISTS `Portal`.`usuarios_bloqueados` (
  `usuario_idUsuario` INT NOT NULL,
  `idUsuarioBloqueado` INT NOT NULL,
  `bloqueadoTotal` TINYINT(1) NOT NULL,
  `bloqueadoParcial` TINYINT(1) NOT NULL,
  INDEX `fk_usuarios_bloqueados_usuario1_idx` (`usuario_idUsuario` ASC),
  PRIMARY KEY (`usuario_idUsuario`),
  UNIQUE INDEX `idUsuarioBloqueado_UNIQUE` (`idUsuarioBloqueado` ASC),
  CONSTRAINT `fk_usuarios_bloqueados_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `Portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`comentarios_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`comentarios_posts` ;

CREATE TABLE IF NOT EXISTS `Portal`.`comentarios_posts` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idPostComentario` INT NOT NULL,
  `idUsuarioComentario` INT NOT NULL,
  `imgUsuarioComentario` VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `tituloComentario` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `comentarioPost` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `ciudadComentario` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `fechaComentario` DATE NOT NULL,
  PRIMARY KEY (`idComentario`),
  UNIQUE INDEX `idComentario_UNIQUE` (`idComentario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`busquedas_pbs_buscadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`busquedas_pbs_buscadas` ;

CREATE TABLE IF NOT EXISTS `Portal`.`busquedas_pbs_buscadas` (
  `idPbsBuscada` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `palabrasBuscadas` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idPbsBuscada`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`busquedas_pbs_ofrecidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`busquedas_pbs_ofrecidas` ;

CREATE TABLE IF NOT EXISTS `Portal`.`busquedas_pbs_ofrecidas` (
  `idPbsOfrecida` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `palabrasOfrecidas` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idPbsOfrecida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`subsecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`subsecciones` ;

CREATE TABLE IF NOT EXISTS `Portal`.`subsecciones` (
  `idsubsecciones` INT NOT NULL AUTO_INCREMENT,
  `secciones_idSecciones` TINYINT(20) NOT NULL,
  `nombreSubseccion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`idsubsecciones`, `secciones_idSecciones`),
  INDEX `fk_subsecciones_secciones1_idx` (`secciones_idSecciones` ASC),
  CONSTRAINT `fk_subsecciones_secciones1`
    FOREIGN KEY (`secciones_idSecciones`)
    REFERENCES `Portal`.`secciones` (`idSecciones`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`usariosMensajesPorNoActivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`usariosMensajesPorNoActivos` ;

CREATE TABLE IF NOT EXISTS `Portal`.`usariosMensajesPorNoActivos` (
  `idusariosMensajesPorNoActivos` INT NOT NULL AUTO_INCREMENT,
  `idUsuarioNoActivo` INT NOT NULL,
  `idUsuariosActivo` INT NOT NULL,
  PRIMARY KEY (`idusariosMensajesPorNoActivos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
