-- MySQL Script generated by MySQL Workbench
-- 05/17/16 20:06:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Portal` ;

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portal` DEFAULT CHARACTER SET utf8 ;
USE `Portal` ;

-- -----------------------------------------------------
-- Table `Portal`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Portal`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `password` CHAR(12) CHARACTER SET 'utf8' BINARY NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `fecha` DATE NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`genero` ;

CREATE TABLE IF NOT EXISTS `Portal`.`genero` (
  `idGenero` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(10) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`datos_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`datos_usuario` ;

CREATE TABLE IF NOT EXISTS `Portal`.`datos_usuario` (
  `idDatosUsuario` INT NOT NULL,
  `idGenero` TINYINT(1) NOT NULL,
  `nombre` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `apellido_1` VARCHAR(25) CHARACTER SET 'utf8' NULL,
  `apellido_2` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `telefono` CHAR(9) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idDatosUsuario`, `idGenero`),
  CONSTRAINT `fk_datos_usuario_genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `Portal`.`genero` (`idGenero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`provincias` ;

CREATE TABLE IF NOT EXISTS `Portal`.`provincias` (
  `idProvincias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idProvincias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`direccion` ;

CREATE TABLE IF NOT EXISTS `Portal`.`direccion` (
  `idDireccion` INT NOT NULL,
  `calle` VARCHAR(25) CHARACTER SET 'utf8' NULL,
  `numeroPortal` VARCHAR(10) CHARACTER SET 'utf8' NULL,
  `ptr` VARCHAR(10) CHARACTER SET 'utf8' NULL,
  `codigoPostal` CHAR(5) CHARACTER SET 'utf8' NULL,
  `ciudad` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `provincias_idprovincias` INT NOT NULL,
  `pais` VARCHAR(25) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idDireccion`, `provincias_idprovincias`),
  INDEX `fk_direccion_provincias1_idx` (`provincias_idprovincias` ASC),
  CONSTRAINT `fk_direccion_provincias1`
    FOREIGN KEY (`provincias_idprovincias`)
    REFERENCES `Portal`.`provincias` (`idProvincias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`secciones` ;

CREATE TABLE IF NOT EXISTS `Portal`.`secciones` (
  `idSecciones` TINYINT(20) NOT NULL AUTO_INCREMENT,
  `nombre_seccion` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idSecciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`post` ;

CREATE TABLE IF NOT EXISTS `Portal`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `secciones_idsecciones` TINYINT(20) NOT NULL,
  `titulo` VARCHAR(30) CHARACTER SET 'utf8' NULL,
  `comentario` VARCHAR(255) CHARACTER SET 'utf8' NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idPost`, `idUsuario`, `secciones_idsecciones`),
  INDEX `fk_post_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_post_secciones1_idx` (`secciones_idsecciones` ASC),
  CONSTRAINT `fk_post_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Portal`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_secciones1`
    FOREIGN KEY (`secciones_idsecciones`)
    REFERENCES `Portal`.`secciones` (`idSecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`pbs_buscadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`pbs_buscadas` ;

CREATE TABLE IF NOT EXISTS `Portal`.`pbs_buscadas` (
  `idBuscadas` INT NOT NULL AUTO_INCREMENT,
  `palabra` VARCHAR(55) CHARACTER SET 'utf8' NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idBuscadas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`pbs_queridas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`pbs_queridas` ;

CREATE TABLE IF NOT EXISTS `Portal`.`pbs_queridas` (
  `idQueridas` INT NOT NULL AUTO_INCREMENT,
  `palabra` VARCHAR(55) CHARACTER SET 'utf8' NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idQueridas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Portal`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Portal`.`imagenes` ;

CREATE TABLE IF NOT EXISTS `Portal`.`imagenes` (
  `post_idPost` INT NOT NULL,
  `post_idUsuario` INT NOT NULL,
  `post_secciones_idsecciones` TINYINT(20) NOT NULL,
  `idImagen` INT NOT NULL,
  `ruta` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `texto` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`post_idPost`, `post_idUsuario`, `post_secciones_idsecciones`),
  CONSTRAINT `fk_imagenes_post1`
    FOREIGN KEY (`post_idPost` , `post_idUsuario` , `post_secciones_idsecciones`)
    REFERENCES `Portal`.`post` (`idPost` , `idUsuario` , `secciones_idsecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
